version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test12345-"
      MSSQL_PID: "Developer"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Test12345-" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - "1443:1433"
  sampleapp-migrations:
    image: ${DOCKER_REGISTRY-}sampleapp-migrations
    build:
      context: .
      dockerfile: SampeApp.Database.Migrations/Dockerfile
    command: ["dotnet", "SampeApp.Database.Migrations.dll"] #, "-up", "--seed"]
    environment:
      - ASPNETCORE_ENVIRONMENT=k8s
      - ConnectionStrings__SampleAppDb=Server=192.168.178.22,1443;Database=SampleApp;User Id=sa;Password=Test12345-;
    depends_on:
      - sql-server
    deploy:
        restart_policy:
          condition: on-failure
  #sampleapp:
  #  image: ${DOCKER_REGISTRY-}sampleapp
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=k8s
  #    - ASPNETCORE_URLS=http://+:80
  #  ports:
  #    - "5500:80"
  #  build:
  #    context: .
  #    dockerfile: SampleApp/Dockerfile